project:
  type: website

website:
  title: "Data Portfolio"
  navbar:
    center:
      - href:
    left:
      - href: index.qmd
        text: Services
      - about.qmd
      - href: index.qmd
        text: Portfolio
      - href: index.qmd
        text: Contact

    right:
      - href: Resume.qmd
      
format:
  html:
    theme: sketchy
    css: styles.css
    toc: true

editor: visual
